#!/bin/bash

echo "Question 1: List the top 10 web sites from which requests came (non-404 status, external addresses looking in)."
echo "count website"
curl -s http://users.csc.tntech.edu/~elbrown/access_log.bz2 | bunzip2 - | awk '$9 != 404 {print}' | awk '$11 ~ /^\"https?:\/\/users.csc.tntech.edu/ {next}{print}' | awk '$11 ~ /\"-\"/ {next}{print $11}' | sed '/^$/d' | sort | uniq -c | sort -nr | head -n 10
echo " "

echo "Question 2: List the top 10 local web pages requested (non-404 status)."
echo "count webpage"
curl -s http://users.csc.tntech.edu/~elbrown/access_log.bz2 | bunzip2 - | awk '$9 != 404 {print}' | awk '{print $7}' | sort | uniq -c | sort -nr | head -n 10
echo " "

echo "Question 3: List the top 10 web browsers used to access the site. It is not necessary to get fancy and parse out all of the browser string. Simply print out the information that is there. Display the percentage of all browser types that each line represents."
echo "percent browser"
n=`curl -s http://users.csc.tntech.edu/~elbrown/access_log.bz2 | bunzip2 - | wc -l`
curl -s http://users.csc.tntech.edu/~elbrown/access_log.bz2 | bunzip2 - | cut -f12- -d " " | sed '/^$/d' | sort | uniq -c | sort -nr | head -n 10 | awk -v "n=$n" '{first = $1; $1 = ""; print first/n*100"%", $0}'
echo " "

echo "Question 4: List the number of 404 errors that were reported in the log."
curl -s http://users.csc.tntech.edu/~elbrown/access_log.bz2 | bunzip2 - | awk '$9 == 404 {print}' | wc -l
echo " "

echo "Question 5: List the number of 500 errors that were reported in the log."
curl -s http://users.csc.tntech.edu/~elbrown/access_log.bz2 | bunzip2 - | awk '$9 == 500 {print}' | wc -l
echo " "

echo "Question 6: What time of day is the site active? When is it quiet? "
echo "count hour"
curl -s http://users.csc.tntech.edu/~elbrown/access_log.bz2 | bunzip2 - | awk '{print $4}' | cut -d':' -f 2 | sort | uniq -c | sort -nr | head -n 24
echo "From the result we found that the site is active during the day, and quiet during the night. 3:00 p.m. is the most active period."
echo " "

echo "Question 7: Is the traffic \"real\" or mostly the result of robots or automated processes?"
n=`curl -s http://users.csc.tntech.edu/~elbrown/access_log.bz2 | bunzip2 - | wc -l`
echo "We have" $n "requests in total. I have calculated the number of requests with some key words like 'robot', 'bot', 'crawler', 'spider', 'wanderer' in the User Agent field." 
tmp=`curl -s http://users.csc.tntech.edu/~elbrown/access_log.bz2 | bunzip2 - | cut -f12- -d " " | grep -i -E "robot|bot|crawler|spider|wanderer" | wc -l`
echo "At least" $tmp "of them are generated by robots."
echo " "
